# Generated by Django 5.2.12 on 2026-03-24 15:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('excerpt', models.TextField(blank=True)),
                ('body', models.TextField()),
                ('cover_image_url', models.URLField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured_home', models.BooleanField(default=False)),
                ('home_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured_home', models.BooleanField(default=False)),
                ('home_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=255)),
                ('author_email', models.EmailField(blank=True, max_length=254)),
                ('quote', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('is_featured_home', models.BooleanField(default=False)),
                ('home_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='addon',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-start_time']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='addon',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='addon',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='total_duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appointment',
            name='total_price_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='service',
            name='available_add_ons',
            field=models.ManyToManyField(blank=True, related_name='services', to='api.addon'),
        ),
        migrations.AddField(
            model_name='service',
            name='home_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='is_featured_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='payment_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='addon',
            index=models.Index(fields=['sort_order'], name='api_addon_sort_or_d075ed_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['sort_order'], name='api_service_sort_or_41423c_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_featured_home', 'home_order'], name='api_service_is_feat_82b3c9_idx'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='portfolioitem',
            index=models.Index(fields=['is_published'], name='api_portfol_is_publ_637037_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioitem',
            index=models.Index(fields=['is_featured_home', 'home_order'], name='api_portfol_is_feat_588670_idx'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='api.service'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['is_published'], name='api_blogpos_is_publ_5a939c_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['is_featured_home', 'home_order'], name='api_blogpos_is_feat_e29aad_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['status'], name='api_testimo_status_264e2a_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['is_featured_home', 'home_order'], name='api_testimo_is_feat_9fb5bc_idx'),
        ),
    ]
