# Generated by Django 5.2.12 on 2026-04-01 09:45

import django.contrib.postgres.constraints
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blogpost_portfolioitem_testimonial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentEmailNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('BOOKING_CREATED', 'Booking Created'), ('BOOKING_RESCHEDULED', 'Booking Rescheduled'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('BOOKING_NO_SHOW', 'Booking No Show')], max_length=32)),
                ('recipient_type', models.CharField(choices=[('CLIENT', 'Client'), ('OWNER', 'Owner')], max_length=16)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('provider', models.CharField(default='RESEND', max_length=32)),
                ('provider_message_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('BOUNCED', 'Bounced'), ('COMPLAINED', 'Complained'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('last_event_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 'CANCELLED'), _negated=True), expressions=[(models.Func(models.F('start_time'), models.F('end_time'), models.Value('[)'), function='TSTZRANGE'), '&&')], name='prevent_overlapping_active_appointments'),
        ),
        migrations.AddField(
            model_name='appointmentemailnotification',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_notifications', to='api.appointment'),
        ),
        migrations.AddIndex(
            model_name='appointmentemailnotification',
            index=models.Index(fields=['appointment', 'event_type'], name='api_appoint_appoint_a54e38_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentemailnotification',
            index=models.Index(fields=['status'], name='api_appoint_status_10df65_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentemailnotification',
            index=models.Index(fields=['recipient_email'], name='api_appoint_recipie_2a168f_idx'),
        ),
    ]
